### ISSUE TITLE
Cannot export private key from bnbcli

### ISSUE THREAD

**Issue by tdiesler** [binance-chain/bsc-relayer#31]
The config asks me to provide a private key like this ...

```
Please fill proper bsc private key to bsc_config.private_key, example private key: 5576779EB3F28F1067BE07AC643A81A8C74E6C55EDE38BEEF68BE1E9D4C1CA3C
```

and I  have successfully generated a key pair with bnbcli like this ...

```
bnbcli keys add test1
...
NAME:   TYPE:   ADDRESS:                                                PUBKEY:
test1   local   bnb1kh75mt60luy00z5tqxefq825e2pwz3cg55wxaa      bnbp1addwnpepqg3wcksplyn5s8mkm28akhvznagdt0067w3tpy8v29cc5ctcrnepjayuacs
```

How can I now export the private key hex? I've got the mnemonic, but not the hex required by the config.

I could perhaps use https://iancoleman.io/bip39, but isn't there a native way to see the PK hex using BSC tooling?
Also, https://iancoleman.io/bip39 doesn't know about BNB

**Comment by yutianwu** [comment]
you can not export private key from bnbcli, you can export you private key via metamask

**Comment by tdiesler** [comment]
This should be properly documented (how) before closing this issue. As it stands now, it is not clear from the main README where the private key entry to the config is supposed to be coming from.
