### ISSUE TITLE
unconfirmed_tx_threshold of Binance Smart Chain should be larger than 0

### ISSUE THREAD

**Issue by tdiesler** [binance-chain/bsc-relayer#32]
With the v1.1.0 default config, I see ...

```
unconfirmed_tx_threshold of Binance Smart Chain should be larger than 0
...
goroutine 1 [running]:
github.com/binance-chain/bsc-relayer/config.(*BSCConfig).Validate(0xc0000da2a0)
	/opt/app/config/config.go:122 +0x24c
github.com/binance-chain/bsc-relayer/config.(*Config).Validate(0xc0000da200)
	/opt/app/config/config.go:201 +0x8a
github.com/binance-chain/bsc-relayer/config.ParseConfigFromFile(0x7fffe05c4e10, 0x1b, 0xb)
	/opt/app/config/config.go:225 +0xe2
main.main()
	/opt/app/main.go:90 +0x131
```

**Comment by yutianwu** [comment]
you need to add `unconfirmed_tx_threshold` in your config.toml

**Comment by moesaleh** [comment]
@yutianwu What's the recommended threshold?

**Comment by yutianwu** [comment]
depends on you, like hundreds?

**Comment by moesaleh** [comment]
What's the consequences of putting 1 or 100?

**Comment by yutianwu** [comment]
just put it to 500

**Comment by moesaleh** [comment]
Thanks a lot @yutianwu

**Comment by tdiesler** [comment]
Again, this should be properly documented before closing this issue. As it stands now, it is not clear from the main README how to configure the Relayer properly.

Perhaps, you could work through a fresh setup and verify that the docs are correct/complete.
