### ISSUE TITLE
Source and Destination Chain ID

### ISSUE THREAD

**Issue by moesaleh** [binance-chain/bsc-relayer#33]
Hello,
What's the recommended source and destination id?
I used this:
"cross_chain_config": {
    "source_chain_id": 1,
    "dest_chain_id": 56,
    "monitor_channel_list": [1, 2, 3, 8, 9],
    "competition_mode": true

but it generates a lot of transaction errors, I appreciate your response

**Comment by yutianwu** [comment]
it's right

**Comment by moesaleh** [comment]
It generated a lot of transactions with errors when I used this configuration, I just need to understand what's the cause of the transactions errors?
