### ISSUE TITLE
Errors on Transactions

### ISSUE THREAD

**Issue by moesaleh** [binance-chain/bsc-relayer#35]
Hello,
What's the reason behind these errors?
What's am doing wrong here?
Here below a screenshot of the error
![image](https://user-images.githubusercontent.com/9066828/123740301-de477200-d8b0-11eb-86f8-bef4587e6417.png)

And the configuration is below here:
{
  "cross_chain_config": {
    "source_chain_id": 1,
    "dest_chain_id": 56,
    "monitor_channel_list": [1, 2, 3, 8, 9],
    "competition_mode": false
  },
  "bbc_config": {
    "rpc_addrs": [
      "tcp://dataseed1.ninicoin.io:80"
    ],
    "mnemonic_type": "local_mnemonic",
    "aws_region": "",
    "aws_secret_name": "",
    "mnemonic": "********************************************",
    "sleep_millisecond_for_wait_block": 500,
    "clean_up_block_interval": 200,
    "block_interval_for_clean_up_undelivered_packages": 5000,
    "behind_block_threshold": 5
  },
  "bsc_config": {
    "key_type": "local_private_key",
    "aws_region": "",
    "aws_secret_name": "",
    "private_key": "**************************",
    "providers": [
      "https://hidden-silent-sun.bsc.quiknode.pro/08daccd148986f3c1611f989c755c4b0aa340b7c/"
    ],
    "gas_limit": 4700000,
    "gas_price": 5000000000,
    "unconfirmed_tx_threshold": 500,
    "monitor_data_seed_list": [

**Comment by moesaleh** [comment]
@yutianwu most of the failed transactions are related to the Cross Chain contract (HandlePackage function), is it related to the socket issues with the BC nodes? or it's a different issue?

**Comment by yutianwu** [comment]
there are many community members runing bsc relayer, so your txs were failed.
