### ISSUE TITLE
Gas Fees and Gas Limit and competition mode

### ISSUE THREAD

**Issue by moesaleh** [binance-chain/bsc-relayer#36]
Hello Again,
I have few questions:
1- Can I modify the gas fees and limit and what's the implication of doing that? and what's the relation between the gas fees/price and the unconfirmed_tx_threshold? When I ran it, the transaction fees were very expensive!
 "gas_limit": 4700000,
    "gas_price": 5000000000,
    "unconfirmed_tx_threshold": 500,

2-  "competition_mode": false/true
What's the recommended mode? and if I set it to false, what's gonna happen in terms of rewards? is the relayer gonna be considered during the rewards distribution? and what's the effects on the rewards?
@yutianwu I appreciate your help here

**Comment by yutianwu** [comment]
this repo is designed to make sure the cross chain txs are relayed in time, but not optimized for community competition. so you should read the code and do your own optimizition.
