### ISSUE TITLE
Testnet faucet only issues 1 BNB per day

### ISSUE THREAD

**Issue by tdiesler** [binance-chain/bsc-relayer#37]
How can we fund the relayer with 100+ BNB for testing?

https://testnet.binance.org/faucet-smart

**Comment by yutianwu** [comment]
then use real BNB

**Comment by tdiesler** [comment]
I'm running the testnet. Could you perhaps transfer testnet 150 BNB to 0xF9051BDcD6996e300207A8Cbe3a6cFB0d0726e1E

**Comment by yutianwu** [comment]
I think you can solve it by your own and you can  test on the mainnet
